// ruru-jinro.net 標準配役プリセット
// 出典: https://ruru-jinro.net/cast.jsp?p=kind
//
// 4 つのカテゴリ (A: 標準 / B: 少人数向け / C: 役職多め / D: 特殊役職) を、人数 4〜30 で抽出。
// 各人数につき、サイト末尾注釈「猫又有りの場合、村人－２、人狼＋１、猫又＋１」を適用した
// 「-neko」バリアントも併せて生成する (村人 >= 2 のときのみ)。
// 範囲記法 (例: 村人 2～3 / 占い師 1～0) は、合計人数を保つ連動した選択肢として
// -v1 / -v2 サフィックスで分割している。
//
// revoteConfig は ruru 標準ルールとして 14D 猫と同じ既定値 (maxRevotes: 2, full_revote, draw) を
// 全件に付与している。
//
// 一部の人気配役には、atwiki ruru_werewolf wiki の人気配役解説 (勝率・所要時間・特徴)
// を meta フィールドとして付与している。出典: https://w.atwiki.jp/ruru_werewolf/pages/83.html
// 機械学習における仮目標値として利用することを想定している。
//
// 未マップ (atwiki に解説はあるが、現行 ruru.ts シナリオに対応する配役が無い項目):
//   - 6B  (村3/狼1/占1/狐1): 現行 ruru-B-6 と配役不一致 (ruru-B-6 は狐の代わりに werehamster)
//
// 対応シナリオはあるが、特殊フラグ (聴狂人 / 強化能力など) が現状の Scenario 型で
// 表現できないため、description に注記している項目:
//   - 12C聴狂人 -> ruru-C-12
//   - 12D聴狂人 -> ruru-D-12
//   - 30C強化猫 -> ruru-C-30-neko

import type { Scenario } from '../scenarios.ts'

const defaultRevoteConfig = { maxRevotes: 2, style: 'full_revote' as const, tiebreaker: 'draw' as const }

const atwikiSource = { url: 'https://w.atwiki.jp/ruru_werewolf/pages/83.html', name: 'るる鯖 人気配役解説 (atwiki)' } as const

export const ruruScenarios: Scenario[] = [
  {
    name: 'ruru-A-4-v1',
    roles: { werewolf: 1, villager: 2, seer: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '4A',
      description: '縮小村や集まった村でよく見かける最低人数配役。発言を引出し役職を見極めるのがポイント。',
      winRate: { village: 0.4518, werewolf: 0.5418, fox: 0, draw: 0.0064 },
      gameTimeMin: 5,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-4-v1-neko', roles: { werewolf: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-4-v2',
    roles: { werewolf: 1, villager: 3 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '4A',
      description: '縮小村や集まった村でよく見かける最低人数配役。発言を引出し役職を見極めるのがポイント。',
      winRate: { village: 0.4518, werewolf: 0.5418, fox: 0, draw: 0.0064 },
      gameTimeMin: 5,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-4-v2-neko', roles: { werewolf: 2, villager: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-5', roles: { werewolf: 1, villager: 3, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-5-neko', roles: { werewolf: 2, villager: 1, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-6', roles: { werewolf: 1, villager: 4, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-6-neko', roles: { werewolf: 2, villager: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-7', roles: { werewolf: 1, villager: 5, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-7-neko', roles: { werewolf: 2, villager: 3, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-8-v1', roles: { werewolf: 2, villager: 5, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-8-v1-neko', roles: { werewolf: 3, villager: 3, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-8-v2', roles: { werewolf: 1, villager: 6, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-8-v2-neko', roles: { werewolf: 2, villager: 4, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-9', roles: { werewolf: 2, villager: 5, seer: 1, medium: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-9-neko', roles: { werewolf: 3, villager: 3, seer: 1, medium: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-10', roles: { werewolf: 2, possessed: 1, villager: 5, seer: 1, medium: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-10-neko', roles: { werewolf: 3, possessed: 1, villager: 3, seer: 1, medium: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-11',
    roles: { werewolf: 2, possessed: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '11A',
      description: '人外が3名、狐も存在しないシンプルな配役。わかりやすいため、初心者にも人気である。',
      winRate: { village: 0.5302, werewolf: 0.3939, fox: 0, draw: 0.0759 },
      gameTimeMin: 40,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-11-neko', roles: { werewolf: 3, possessed: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-12', roles: { werewolf: 2, possessed: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-12-neko',
    roles: { werewolf: 3, possessed: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '12A猫',
      description: 'シンプルなA配役で猫が楽しめることで、人気が上昇した。11Aとも12Bとも違う多様なゲーム性が楽しめる配役。',
      winRate: { village: 0.4630, werewolf: 0.4838, fox: 0, draw: 0.0532 },
      gameTimeMin: 40,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-13', roles: { werewolf: 2, possessed: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-13-neko', roles: { werewolf: 3, possessed: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-14', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-14-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-15', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-15-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-16',
    roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '16A',
      description: '17Aから村人を一人減らした配役。基本は17Aと同じ。奇数進行からスタートするため、人外が少々有利になる。',
      winRate: { village: 0.4547, werewolf: 0.3158, fox: 0.1564, draw: 0.0731 },
      gameTimeMin: 80,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-16-neko', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-17',
    roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '17A',
      description: '"普通村"といえばこれ。わかめて鯖でも楽しまれているオーソドックスな配役。戦略の幅の広さや、自由なプレイスタイルを受け入れる風潮が魅力。',
      winRate: { village: 0.5066, werewolf: 0.2936, fox: 0.1241, draw: 0.0756 },
      gameTimeMin: 80,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-17-neko', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-18', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-A-18-neko',
    roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '18A猫',
      description: '17Aから村人を1名抜いて狼と猫又を追加した配役。猫又を楽しめる。また狼が4名いるため色々な戦術をとれる。',
      winRate: { village: 0.5106, werewolf: 0.2752, fox: 0.1175, draw: 0.0957 },
      gameTimeMin: 100,
      source: atwikiSource,
    },
  },
  { name: 'ruru-A-19', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-19-neko', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-20', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-20-neko', roles: { werewolf: 5, possessed: 1, werehamster: 1, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-21', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-21-neko', roles: { werewolf: 5, possessed: 1, werehamster: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-22', roles: { werewolf: 4, possessed: 1, werehamster: 1, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-22-neko', roles: { werewolf: 5, possessed: 1, werehamster: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-23', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-23-neko', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-24', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-24-neko', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-25', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-25-neko', roles: { werewolf: 6, possessed: 1, werehamster: 2, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-26', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 13, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-26-neko', roles: { werewolf: 6, possessed: 1, werehamster: 2, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-27', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 14, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-27-neko', roles: { werewolf: 6, possessed: 1, werehamster: 2, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-28', roles: { werewolf: 5, possessed: 2, werehamster: 2, villager: 13, seer: 1, medium: 1, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-28-neko', roles: { werewolf: 6, possessed: 2, werehamster: 2, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-29', roles: { werewolf: 6, possessed: 2, werehamster: 2, villager: 13, seer: 1, medium: 1, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-29-neko', roles: { werewolf: 7, possessed: 2, werehamster: 2, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-30', roles: { werewolf: 7, possessed: 2, werehamster: 2, villager: 12, seer: 1, medium: 1, bodyguard: 2, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-A-30-neko', roles: { werewolf: 8, possessed: 2, werehamster: 2, villager: 10, seer: 1, medium: 1, bodyguard: 2, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-4-v1', roles: { werewolf: 1, villager: 2, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-4-v1-neko', roles: { werewolf: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-4-v2', roles: { werewolf: 1, villager: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-4-v2-neko', roles: { werewolf: 2, villager: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-5', roles: { werewolf: 1, werehamster: 1, villager: 2, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-5-neko', roles: { werewolf: 2, werehamster: 1, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-6', roles: { werewolf: 1, werehamster: 1, villager: 3, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-6-neko', roles: { werewolf: 2, werehamster: 1, villager: 1, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-7', roles: { werewolf: 1, werehamster: 1, villager: 4, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-7-neko', roles: { werewolf: 2, werehamster: 1, villager: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-8-v1', roles: { werewolf: 1, possessed: 1, werehamster: 1, villager: 4, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-8-v1-neko', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-8-v2', roles: { werewolf: 1, werehamster: 1, villager: 5, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-8-v2-neko', roles: { werewolf: 2, werehamster: 1, villager: 3, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-9', roles: { werewolf: 2, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-9-neko', roles: { werewolf: 3, werehamster: 1, villager: 1, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-10', roles: { werewolf: 2, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-10-neko', roles: { werewolf: 3, werehamster: 1, villager: 2, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-11', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-11-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 2, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-B-12',
    roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '12B',
      description: '17Aと人気を二分する定番配役。オーソドックスな人狼を楽しめる。少人数でさくさくとプレイできるため、プレイヤー層が厚く数も多い。',
      winRate: { village: 0.4124, werewolf: 0.3027, fox: 0.1901, draw: 0.0958 },
      gameTimeMin: 40,
      source: atwikiSource,
    },
  },
  { name: 'ruru-B-12-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-13', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-13-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 2, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-14', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-14-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-15', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-15-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-16', roles: { werewolf: 3, possessed: 1, werehamster: 2, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-16-neko', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-17', roles: { werewolf: 3, possessed: 1, werehamster: 2, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-17-neko', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-18', roles: { werewolf: 3, possessed: 1, werehamster: 2, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-18-neko', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-19', roles: { werewolf: 3, possessed: 2, werehamster: 2, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-19-neko', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-20', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-B-20-neko', roles: { werewolf: 5, possessed: 1, werehamster: 2, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-4', roles: { werewolf: 1, villager: 1, seer: 1, medium: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-5', roles: { werewolf: 1, possessed: 1, villager: 1, seer: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-C-6',
    roles: { werewolf: 1, possessed: 3, seer: 1, bodyguard: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '6C',
      description: 'お祭り気分で楽しめる狂人村。村陣営は狼陣営を騙ってPPを回避する事になる。配役を見てうける印象よりも村勝率は高い。',
      winRate: { village: 0.2935, werewolf: 0.6854, fox: 0, draw: 0.0210 },
      gameTimeMin: 5,
      source: atwikiSource,
    },
  },
  { name: 'ruru-C-7', roles: { werewolf: 1, possessed: 1, villager: 2, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-7-neko', roles: { werewolf: 2, possessed: 1, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-C-8',
    roles: { werewolf: 2, possessed: 1, villager: 1, seer: 1, medium: 1, mason: 2 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '8C',
      description: '少人数のFO(フルオープン)村。村人が1名しかいないため、基本的に朝一で挨拶を挟まずに素村も含め全員CO必須(=FO)。このため人外は全員騙りに出る必要がある。',
      winRate: { village: 0.4894, werewolf: 0.4995, fox: 0, draw: 0.0111 },
      gameTimeMin: 15,
      source: atwikiSource,
    },
  },
  { name: 'ruru-C-9', roles: { werewolf: 1, possessed: 1, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-9-neko', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 1, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-10', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 2, seer: 2, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-C-10-neko',
    roles: { werewolf: 3, possessed: 1, werehamster: 1, seer: 2, medium: 1, bodyguard: 1, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '10C猫',
      description: 'お祭りFO村。10Cは人外有利。最近はあまり見かけないが猫狩含めて少人数でFO村を楽しめる。',
      winRate: { village: 0.2265, werewolf: 0.4530, fox: 0.2778, draw: 0.0427 },
      gameTimeMin: 25,
      source: atwikiSource,
    },
  },
  { name: 'ruru-C-11', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 3, seer: 2, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-C-11-neko',
    roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 1, seer: 2, medium: 1, bodyguard: 1, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '11C猫',
      description: 'お祭りFO村。11Cはバランス配役。最近はあまり見かけないが猫狩含めて少人数でFO村を楽しめる。',
      winRate: { village: 0.3770, werewolf: 0.3770, fox: 0.1962, draw: 0.0492 },
      gameTimeMin: 30,
      source: atwikiSource,
    },
  },
  {
    name: 'ruru-C-12',
    roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '12C聴狂人',
      description: '聴狂人有りという設定が魅力。潜伏狂人や漂白噛みなどその設定を生かした戦略を楽しめる。共有者が存在しており、グレーがかなり狭いため潜伏力が試される配役 (注: 本シナリオは聴狂人フラグ未対応で通常狂人として扱われる)。',
      winRate: { village: 0.4854, werewolf: 0.2997, fox: 0.1104, draw: 0.1045 },
      gameTimeMin: 40,
      source: atwikiSource,
    },
  },
  { name: 'ruru-C-12-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 1, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-13', roles: { werewolf: 2, possessed: 1, werehamster: 1, villager: 3, seer: 2, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-13-neko', roles: { werewolf: 3, possessed: 1, werehamster: 1, villager: 1, seer: 2, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-14', roles: { werewolf: 2, possessed: 2, werehamster: 1, villager: 3, seer: 2, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-14-neko', roles: { werewolf: 3, possessed: 2, werehamster: 1, villager: 1, seer: 2, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-15', roles: { werewolf: 3, possessed: 2, werehamster: 1, villager: 3, seer: 2, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-15-neko', roles: { werewolf: 4, possessed: 2, werehamster: 1, villager: 1, seer: 2, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-16', roles: { werewolf: 3, possessed: 1, werehamster: 2, villager: 4, seer: 2, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-16-neko', roles: { werewolf: 4, possessed: 1, werehamster: 2, villager: 2, seer: 2, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-17', roles: { werewolf: 3, possessed: 2, werehamster: 2, villager: 3, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-17-neko', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 1, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-18', roles: { werewolf: 3, possessed: 2, werehamster: 2, villager: 4, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-18-neko', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 2, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-19', roles: { werewolf: 3, possessed: 2, werehamster: 2, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-19-neko', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 3, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-20', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-20-neko', roles: { werewolf: 5, possessed: 2, werehamster: 2, villager: 3, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-21', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 6, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-21-neko', roles: { werewolf: 5, possessed: 2, werehamster: 2, villager: 4, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-22', roles: { werewolf: 4, possessed: 2, werehamster: 2, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-22-neko', roles: { werewolf: 5, possessed: 2, werehamster: 2, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-23', roles: { werewolf: 5, possessed: 2, werehamster: 2, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-23-neko', roles: { werewolf: 6, possessed: 2, werehamster: 2, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-24', roles: { werewolf: 5, possessed: 2, werehamster: 3, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-24-neko', roles: { werewolf: 6, possessed: 2, werehamster: 3, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-25', roles: { werewolf: 5, possessed: 2, werehamster: 3, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-25-neko', roles: { werewolf: 6, possessed: 2, werehamster: 3, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-26', roles: { werewolf: 5, possessed: 3, werehamster: 3, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-26-neko', roles: { werewolf: 6, possessed: 3, werehamster: 3, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-27', roles: { werewolf: 6, possessed: 3, werehamster: 3, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-27-neko', roles: { werewolf: 7, possessed: 3, werehamster: 3, villager: 5, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-28', roles: { werewolf: 6, possessed: 3, werehamster: 3, villager: 8, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-28-neko', roles: { werewolf: 7, possessed: 3, werehamster: 3, villager: 6, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-29', roles: { werewolf: 7, possessed: 3, werehamster: 3, villager: 8, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-29-neko', roles: { werewolf: 8, possessed: 3, werehamster: 3, villager: 6, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-C-30', roles: { werewolf: 7, possessed: 3, werehamster: 3, villager: 9, seer: 2, medium: 2, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-C-30-neko',
    roles: { werewolf: 8, possessed: 3, werehamster: 3, villager: 7, seer: 2, medium: 2, bodyguard: 1, mason: 3, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '30C強化猫',
      description: 'るる鯖の最大人数でできる大人数村。強化能力による三つ巴になっている。役職が多いため、柔軟な思考が求められる (注: 本シナリオは強化フラグ未対応で通常役職として扱われる)。',
      winRate: { village: 0.2026, werewolf: 0.3922, fox: 0.3137, draw: 0.0915 },
      gameTimeMin: 80,
      source: atwikiSource,
    },
  },
  { name: 'ruru-D-4-v1', roles: { werewolf: 1, villager: 2, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-4-v1-neko', roles: { werewolf: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-4-v2', roles: { werewolf: 1, villager: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-4-v2-neko', roles: { werewolf: 2, villager: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-5', roles: { werewolf: 1, villager: 3, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-5-neko', roles: { werewolf: 2, villager: 1, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-6', roles: { werewolf: 1, possessed: 2, fanatic: 1, seer: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-7', roles: { werewolf: 1, villager: 5, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-7-neko', roles: { werewolf: 2, villager: 3, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-8-v1', roles: { werewolf: 2, villager: 5, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-8-v1-neko', roles: { werewolf: 3, villager: 3, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-8-v2', roles: { werewolf: 1, villager: 6, seer: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-8-v2-neko', roles: { werewolf: 2, villager: 4, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-D-9',
    roles: { werewolf: 1, werehamster: 1, immoralist: 2, villager: 4, seer: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '9D',
      description: '狐勝率がとび抜けているこんこんおきちゅね村。背徳者が2名いるため、いかに狐処理を行うかが重要になる。',
      winRate: { village: 0.2539, werewolf: 0.2550, fox: 0.4065, draw: 0.0846 },
      gameTimeMin: 15,
      source: atwikiSource,
    },
  },
  { name: 'ruru-D-9-neko', roles: { werewolf: 2, werehamster: 1, immoralist: 2, villager: 2, seer: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-10', roles: { werewolf: 2, fanatic: 1, villager: 5, seer: 1, medium: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-10-neko', roles: { werewolf: 3, fanatic: 1, villager: 3, seer: 1, medium: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-11', roles: { werewolf: 2, fanatic: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-11-neko', roles: { werewolf: 3, fanatic: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-D-12',
    roles: { werewolf: 2, fanatic: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '12D聴狂人',
      description: '純粋に人狼vs村人の勝負が楽しめる12人役職。聴狂信により狼側の戦略幅が広く有利。誤爆がなく運要素が大幅に減っているため、村人陣営の進行役のセンスが問われる配役 (注: 本シナリオは聴狂人フラグ未対応で通常狂信者として扱われる)。',
      winRate: { village: 0.3846, werewolf: 0.6154, fox: 0, draw: 0 },
      gameTimeMin: 40,
      source: atwikiSource,
    },
  },
  { name: 'ruru-D-12-neko', roles: { werewolf: 3, fanatic: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-13', roles: { werewolf: 2, fanatic: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-13-neko', roles: { werewolf: 3, fanatic: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-14', roles: { werewolf: 2, fanatic: 1, werehamster: 1, immoralist: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-D-14-neko',
    roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 2, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '14D猫',
      description: '6人外6吊りの3陣営三つ巴配役。るる鯖にしかない。狂信者、背徳者、猫も出現し各陣営、様々な戦略が楽しめるところが魅力。',
      winRate: { village: 0.4924, werewolf: 0.2485, fox: 0.1701, draw: 0.0890 },
      gameTimeMin: 50,
      source: atwikiSource,
    },
  },
  { name: 'ruru-D-15', roles: { werewolf: 2, fanatic: 1, werehamster: 1, immoralist: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-15-neko', roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-16', roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-16-neko', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 3, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-17', roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-17-neko', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 4, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-18', roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-18-neko', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 5, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-19', roles: { werewolf: 3, fanatic: 1, werehamster: 1, immoralist: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  {
    name: 'ruru-D-19-neko',
    roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 },
    hasFirstGhost: true,
    revoteConfig: defaultRevoteConfig,
    meta: {
      popularName: '19D猫',
      description: 'オーソドックスなD配役。背徳者、狂信者、猫又がいる。D配役の特殊役職が魅力、推理要素も多い。',
      winRate: { village: 0.4885, werewolf: 0.3103, fox: 0.1332, draw: 0.0690 },
      gameTimeMin: 100,
      source: atwikiSource,
    },
  },
  { name: 'ruru-D-20', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-20-neko', roles: { werewolf: 5, fanatic: 1, werehamster: 1, immoralist: 1, villager: 6, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-21', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-21-neko', roles: { werewolf: 5, fanatic: 1, werehamster: 1, immoralist: 1, villager: 7, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-22', roles: { werewolf: 4, fanatic: 1, werehamster: 1, immoralist: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-22-neko', roles: { werewolf: 5, fanatic: 1, werehamster: 1, immoralist: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-23', roles: { werewolf: 4, fanatic: 1, werehamster: 2, immoralist: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-23-neko', roles: { werewolf: 5, fanatic: 1, werehamster: 2, immoralist: 1, villager: 8, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-24', roles: { werewolf: 4, fanatic: 1, werehamster: 2, immoralist: 1, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-24-neko', roles: { werewolf: 5, fanatic: 1, werehamster: 2, immoralist: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-25', roles: { werewolf: 5, fanatic: 1, werehamster: 2, immoralist: 1, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-25-neko', roles: { werewolf: 6, fanatic: 1, werehamster: 2, immoralist: 1, villager: 9, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-26', roles: { werewolf: 5, fanatic: 1, werehamster: 2, immoralist: 1, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-26-neko', roles: { werewolf: 6, fanatic: 1, werehamster: 2, immoralist: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-27', roles: { werewolf: 5, fanatic: 1, werehamster: 2, immoralist: 1, villager: 13, seer: 1, medium: 1, bodyguard: 1, mason: 2 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-27-neko', roles: { werewolf: 6, fanatic: 1, werehamster: 2, immoralist: 1, villager: 11, seer: 1, medium: 1, bodyguard: 1, mason: 2, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-28', roles: { werewolf: 5, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-28-neko', roles: { werewolf: 6, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-29', roles: { werewolf: 6, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 12, seer: 1, medium: 1, bodyguard: 1, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-29-neko', roles: { werewolf: 7, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 10, seer: 1, medium: 1, bodyguard: 1, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-30', roles: { werewolf: 7, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 11, seer: 1, medium: 1, bodyguard: 2, mason: 3 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
  { name: 'ruru-D-30-neko', roles: { werewolf: 8, possessed: 1, fanatic: 1, werehamster: 2, immoralist: 1, villager: 9, seer: 1, medium: 1, bodyguard: 2, mason: 3, nekomata: 1 }, hasFirstGhost: true, revoteConfig: defaultRevoteConfig },
]
